---

# TODO:
# 1. upload ssh public key
# 2. change ssh default port [done]

- name: Check if we're using the inventory-provided SSH port
  wait_for:
    port: "{{ ansible_port | default(22) }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: default_ssh
  when: SSH_PORT is defined

- name: use new ssh port
  set_fact:
    ansible_ssh_port: "{{ SSH_PORT }}"
  when: default_ssh.failed is defined

- name: get vars
  setup:

- name: playbook only works on CentOS 7
  command: /usr/bin/uptime
  changed_when: False
  failed_when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

- name: set locale
  file:
    src: environment
    dest: /etc/environment
    state: file

- name: change ssh default port if needed
  include: ssh.yml
  when: SSH_PORT is defined and ansible_port != SSH_PORT

- name: Install basic soft
  yum:
    name:
      - libselinux-python
      - vim-enhanced
      - wget
      - net-tools
      - bind-utils
    state: present

- name: Disable SELinux
  selinux:
    state: disabled
  notify: reboot

- name: Disable firwalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: add epel repo
  yum:
    name: epel-release
    state: present

- name: change swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
    sysctl_set: yes

- name: enable fast open
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: 3
    state: present
    reload: yes
    sysctl_set: yes

- name: enable bbr step 1
  sysctl:
    name: net.core.default_qdisc
    value: fq
    state: present

- name: enable bbr step 2
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    state: present