- name: import repo key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: install elrepo
  yum:
    name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

- name: update kernel
  yum:
    name: kernel-ml
    state: absent
    enablerepo: elrepo-kernel
    update_cache: yes
  notify: reboot